name: cicd-workflow with slack integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        id: build_step
        run: mvn install -f MyWebApp/pom.xml

      - name: Slack Notification on Failure
        if: failure()  # ✅ only runs if any previous step failed
        uses: act10ns/slack@v2
        with:
          channel: '#front-end-dashboard'
          status: failure
          text: |
            🚨 *Pipeline Failed*
            *Repository:* ${{ github.repository }}
            *Branch:* ${{ github.ref_name }}
            *Commit:* <https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>
            *Triggered by:* ${{ github.actor }}
            *Workflow:* ${{ github.workflow }}
            *Job:* ${{ github.job }}
            ❗ Check logs to identify failed step.
