name: cicd-workflow with slack integration

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        id: build_step
        run: mvn install -f MyWebApp/pom.xml

      - name: Check failure cause
        id: detect_fail
        run: |
          if [ "${{ steps.build_step.outcome }}" == "failure" ]; then
            echo "FAILED_STEP=Build with Maven" >> $GITHUB_ENV
          fi

      - name: Slack Notification on Failure
        if: failure()
        uses: act10ns/slack@v2
        env:
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
          RUN_ID: ${{ github.run_id }}
          FAILED_STEP: ${{ env.FAILED_STEP || 'Unknown' }}
        with:
          channel: '#front-end-dashboard'
          status: failure
          message: ":rotating_light: *CI/CD Pipeline Failed*\n*Repository:* $REPO\n*Branch:* $BRANCH\n*Commit:* <$REPO/commit/$SHA|$SHA>\n*Triggered by:* $ACTOR\n*Failed Step:* $FAILED_STEP\n*Run:* https://github.com/$REPO/actions/runs/$RUN_ID"
